### ISSUE TITLE
KeyError (key not found: :account_host_key)

### ISSUE THREAD

**Issue by VinothiniBalakrishnan** [swiftype/swiftype-app-search-ruby#24]
client = SwiftypeAppSearch::Client.new(:host_identifier => 'host-XXXXXX', :api_key => 'private-XXXXXXXXXX')
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):1:in `new'
KeyError (key not found: :account_host_key)

No idea Why I am getting this error. Please let me know what I am doing wrong.

When I try the same credentials in cURL works fine. I can see new documentation created successfully.

**Comment by goodroot** [comment]
Hello, @VinothiniBalakrishnan 👋 😃 ~ thanks for checking out the Ruby client.

We made a recent change to fix our naming convention. We re-named the `account_host_key` to `host_identifier`. 

If you are using an older version that is older than `0.3.0`, your client should look like this:

```
client = SwiftypeAppSearch::Client.new(:account_host_key => 'host-XXXXXX', :api_key => 'private-XXXXXXXXXX')
```

If you are using the most recent client, `0.3.0` or later, your client should look like this:

```
client = SwiftypeAppSearch::Client.new(:host_identifier => 'host-XXXXXX', :api_key => 'private-XXXXXXXXXX')
```

Please let me know when you have had a chance to try it out so that we can close the issue.

**Comment by VinothiniBalakrishnan** [comment]
Thanks for the clarification @goodroot 

Now the below one works :)

```gem 'swiftype-app-search', '~> 0.1.3'```

```client = SwiftypeAppSearch::Client.new(:account_host_key => 'host-XXXXXX', :api_key => 'private-XXXXXXXXXX')```

In README I can see

```gem 'swiftype-app-search', '~> 0.1.3 in your Gemfile```

```client = SwiftypeAppSearch::Client.new(:host_identifier => 'host-c5s2mj', :api_key => 'api-mu75psc5egt9ppzuycnc2mc3')```

That is why I tried with ```host_identifier```. I think better we can edit README with your clarification.
